; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
; On ajoute -I include pour forcer la lecture globale du dossier include
build_unflags = -std=gnu++14 -std=gnu++17
build_flags = 
    -D USB_MIDI_AUDIO_SERIAL
    -I include
    -Wno-volatile
    -std=gnu++2a
    -D AUDIO_BLOCK_SAMPLES=48
